# Project information
site_name: Monero Documentation
site_description: 'Unofficial Monero Documentation'
site_author: "Piotr 'Qertoip' Włodarek"
site_url: 'https://monerodocs.org/'

nav:
- Home: 'index.md'
- Interacting:
  - Overview: 'interacting/overview.md'
  - monerod: 'interacting/monerod-reference.md'
- Technical specs: 'technical-specs.md'
- Cryptography:
    - Introduction: 'cryptography/introduction.md'
    - PRNG: 'cryptography/prng.md'
    - 'Keccak-256': 'cryptography/keccak-256.md'
    - Asymmetric:
      - Introduction: 'cryptography/asymmetric/introduction.md'
      - Private keys: 'cryptography/asymmetric/private-key.md'
      - Public keys: 'cryptography/asymmetric/public-key.md'
      - Edwards25519 curve: 'cryptography/asymmetric/edwards25519.md'
      - Key image: 'cryptography/asymmetric/key-image.md'
#    - CryptoNight PoW: 'cryptography/cryptonight.md'
    - Base58: 'cryptography/base58.md'
- Address:
    - Main: 'public-address/main-address.md'
    - Subaddress: 'public-address/subaddress.md'
    - Integrated: 'public-address/integrated-address.md'
- Multisignature: 'multisignature.md'
- Infrastructure:
    - Mainnet, stagenet, testnet: 'infrastructure/networks.md'
    - MoneroPulse: 'infrastructure/monero-pulse.md'

theme:
  name: 'material'
  palette:
#    primary: 'Indigo'
#    primary: 'Deep Orange'
#    primary: 'Orange'
    primary: 'White'
    accent: 'Indigo'
  logo: 'images/monero.svg'
  language: 'en'
#   feature:
#     tabs: true

extra_css: ['extra.css', 'overrides.css']

repo_name: 'monerodocs/md'
repo_url: 'https://github.com/monerodocs/md'

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
